### PR TITLE
Fix serde attribute on redis::ConnectionInfo struct

### PR DESCRIPTION
**Pull request by tyranron**
## Problem

```bash
❯ cargo check -p deadpool-redis --no-default-features --features rt_tokio_1
    Checking deadpool-redis v0.8.1
error: cannot find attribute `serde` in this scope
  --> redis/src/config.rs:97:7
   |
97 |     #[serde(flatten)]
   |       ^^^^^

error: aborting due to previous error

error: could not compile `deadpool-redis`
```

### CODE REVIEW

**Comment by bikeshedder** [comment]
Thanks a lot for working on this. The broken CI has bugged me as well. I just haven't found the time to look into this, yet.

**Comment by tyranron** [comment]
@bikeshedder [`rabbitmq` image](https://hub.docker.com/_/rabbitmq) caused the CI issue:

> WARNING: As of RabbitMQ 3.9, all of the docker-specific variables listed below are deprecated and no longer used. Please use a configuration file instead; visit rabbitmq.com/configure to learn more about the configuration file. For a starting point, the 3.8 images will print out the config file it generated from supplied environment variables.

That was easy fix.

But now I'm trying to cover the case caused this PR in CI, and things there are a bit more complicated with conditional compilation in tests and docs.

**Comment by tyranron** [comment]
Let me some time to mess around with it.

**Comment by bikeshedder** [comment]
I just added #126. It is related to this PR as the `config` feature turned out to be obsolete and should be replaced by a `serde` feature instead.

Feel free to change the feature gates to `#[cfg_attr(feature = "serde", ... )]` already. The `config` feature enables the `serde` feature and therefore this should already work.

**Comment by tyranron** [comment]
@bikeshedder thanks for clarifying. Will consider that in a separate PR.

**Comment by tyranron** [comment]
@bikeshedder ready to merge!

**Comment by bikeshedder** [comment]
Thanks a lot! :+1:

**Pull request merged**
