### PR TITLE
Adds tracing feature flag for deadpool-sync and sqlite.

### PR DESCRIPTION
**Pull request by xfbs**
With deadpool-sqlite, the database interactions happen in a sync context (due to using rusqlite) on a separate thread. The tracing crate can add conetxt to any logs (events). Due to the database interactions happening on a separate thread, this context gets lost. Enabling the tracing feature allows the information to be preserved.

Related: https://github.com/dbrgn/tracing-test/issues/23

Note: I don't know if this is something that should rather be implemented in the `spawn_blocking` method of Tokio.

### CODE REVIEW

**Comment by xfbs** [comment]
@bikeshedder any updates on this? Do you want me to look into the failing checks? It would be nice to get this merged so that tracing can be used properly.

**Comment by xfbs** [comment]
Ping

**Comment by bikeshedder** [comment]
Pong!

I'm on it. I'm very sorry for all the delay. 0.10 was supposed to be released a few weeks ago.
I'll release 0.10 shortly including a bunch of important changes shortly.

This PR will be part of it, too.

**Comment by xfbs** [comment]
Sounds good!

**Pull request merged**
