### PR TITLE
Update redis crate to 0.21

### PR DESCRIPTION
**Pull request by paolobarbolini**

### CODE REVIEW

**Comment by tyranron** [comment]
@bikeshedder would you be so kind to release a new version of `deadpool-redis` crate?

**Comment by bikeshedder** [comment]
I'm a bit hesitant to create a new release just yet as it also includes the new pool builder, hooks, etc. which are rather new and there are still some minor issues I want to tackle (I just created issues for that to remind myself about it):

- #124
- #125

I plan to make a proper release including those two changes within the next few days (probably this weekend).

Are you in a hurry? Alternatively `deadpool-redis 0.9` could be released which just updates `redis` to `0.21` and nothing else.

**Comment by tyranron** [comment]
@bikeshedder 

> Alternatively deadpool-redis 0.9 could be released which just updates redis to 0.21 and nothing else.

That would be perfect! Thanks!

**Comment by bikeshedder** [comment]
I guess that release should also include #122 which fixes the feature gates, no?

**Comment by tyranron** [comment]
@bikeshedder hmm... will `deadpool-redis 0.9` depend on `deadpool 0.9` features in any way? Or it should work OK with `deadpool 0.8`?

> I guess that release should also include #122 which fixes the feature gates, no?

Ok, so I'll reduce that PR and decompose the hard part into another one.

**Comment by bikeshedder** [comment]
I just released `deadpool-redis-v0.9.0` on crates.io: https://crates.io/crates/deadpool-redis/0.9.0

It includes all commits (cherry picked) from `master` except for c0f465da52fff1d34a23d5a932144d10c82d8c86

**Comment by bikeshedder** [comment]
Here is the branch: https://github.com/bikeshedder/deadpool/tree/deadpool-redis-v0.9

**Pull request merged**
