### PR TITLE
Avoid panic and demonstrate how to set values for minimal example

### PR DESCRIPTION
**Pull request by peter-scholtens**
As the default configuration sets all fields to None it will **panic** ("No such file or directory") in all uses cases. A set of simple suggestions and the proper dependencies can help beginners.

### CODE REVIEW

**Comment by bikeshedder** [comment]
The minimum example doesn't panic if you've configured your local PostgreSQL accordingly. PostgreSQL by default creates a unix domain socket at `/run/postgresql/.s.PGSQL.5432` (alternatively: `/var/run/postgresql` or `/tmp`). Those are the three paths which are tried in order:

https://github.com/bikeshedder/deadpool/blob/de5157fe390edd1c332812e0af46cd4905681c60/postgres/src/config.rs#L217-L219

For this to work you just need a database user named the same as your system user and an entry in the `pg_hba.conf` like that:

```
local   all   all   peer
```

Oh, and this only works on unix-like systems. Windows doesn't have the concept of unix domain sockets and therefore doesn't support this. :see_no_evil:

**Comment by bikeshedder** [comment]
Those defaults are virtually identical to `libpq`: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS

Actually even `dbname` could be made optional and default to the system user name as stated in the `libpq` documentation. For some reason I decided that I didn't consider this default useful and made `dbname` mandatory instead.

How about changing the example like that:

> The following example assumes a PostgreSQL reachable via an unix domain socket and peer auth enabled for the local user in [pg_hba.conf](https://www.postgresql.org/docs/current/auth-pg-hba-conf.html). If you're running windows you probably want to specify the `host`, `user` and `password` in the connection config or use an alternative [authentication method](https://www.postgresql.org/docs/current/auth-methods.html).

**Comment by peter-scholtens** [comment]
Okay. And mention the Cargo.toml dependencies, as that was not clear to me at first too.

**Comment by bikeshedder** [comment]
That should be pretty clear for anyone using Rust and Cargo, no? If you don't need any special `tokio-postgres` features you don't even need to add the `tokio-postgres` dependency.

Btw. have you seen the `postgres-hyper` example? https://github.com/bikeshedder/deadpool/tree/master/examples/postgres-hyper

I should create a new example with `axum` though as using `hyper` directly is very basic.

**Pull request closed without merging**
