### PR TITLE
feature: add deadpool-redis-cluster

### LINKED ISSUE #175: Feature request: deadpool_redis support redis cluster
Wish deadpool_redis support redis cluster mode!
like mobc's support: https://crates.io/crates/mobc-redis-cluster

### PR DESCRIPTION
**Pull request by 0xWOF**
- add deadpool-redis-cluster
    - use redis_cluster_async
    - based on deadpool-redis
- add redis-cluster to test-build.sh, README.md, Cargo.toml, ci.yml

closes #175

### CODE REVIEW

**Comment by 0xWOF** [comment]
Sorry for delay. This commit is tested by my local repository's github action. It will pass the test.

**Comment by 0xWOF** [comment]
I should migrate redis_cluster_async to redis after this pull request is merged
- https://github.com/redis-rs/redis-rs/pull/696

**Comment by bikeshedder** [comment]
Ist it okay for you if I merge this, clean things up a bit and push a `0.1.0` version of this to crates.io?

**Comment by 0xWOF** [comment]
@bikeshedder yes!

**Pull request merged**
