### PR TITLE
chore: bump `redis` to 0.26

### PR DESCRIPTION
**Pull request by attila-lin**
Maybe bump a new version?

### CODE REVIEW

**Comment by robjtede** [comment]
keen for a new version with this @bikeshedder 🙏🏻

**Comment by bikeshedder** [comment]
I closed that PR too soon. Something is wrong with the `redis-cluster` tests: https://github.com/bikeshedder/deadpool/actions/runs/10248994809/job/28351446716

**Comment by robjtede** [comment]
ahh dang, no worries, appreciate the info 👍🏻

**Comment by bikeshedder** [comment]
Thanks a lot. :partying_face: 

I just released `deadpool-redis` on `crates.io`:
- [:package: deadpool-redis 0.16.0](https://crates.io/crates/deadpool-redis/0.16.0)

**Pull request merged**
